/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

/// Apiv1ActivityMemoCommentPayload : ActivityMemoCommentPayload represents the payload of a memo comment activity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv1ActivityMemoCommentPayload {
    /// The memo name of comment. Refer to `Memo.name`.
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// The name of related memo.
    #[serde(rename = "relatedMemo", skip_serializing_if = "Option::is_none")]
    pub related_memo: Option<String>,
}

impl Apiv1ActivityMemoCommentPayload {
    /// ActivityMemoCommentPayload represents the payload of a memo comment activity.
    pub fn new() -> Apiv1ActivityMemoCommentPayload {
        Apiv1ActivityMemoCommentPayload {
            memo: None,
            related_memo: None,
        }
    }
}
