/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv1ActivityPayload {
    #[serde(rename = "memoComment", skip_serializing_if = "Option::is_none")]
    pub memo_comment: Option<Box<models::Apiv1ActivityMemoCommentPayload>>,
}

impl Apiv1ActivityPayload {
    pub fn new() -> Apiv1ActivityPayload {
        Apiv1ActivityPayload { memo_comment: None }
    }
}
