/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserStatsMemoTypeStats {
    #[serde(rename = "linkCount", skip_serializing_if = "Option::is_none")]
    pub link_count: Option<i32>,
    #[serde(rename = "codeCount", skip_serializing_if = "Option::is_none")]
    pub code_count: Option<i32>,
    #[serde(rename = "todoCount", skip_serializing_if = "Option::is_none")]
    pub todo_count: Option<i32>,
    #[serde(rename = "undoCount", skip_serializing_if = "Option::is_none")]
    pub undo_count: Option<i32>,
}

impl UserStatsMemoTypeStats {
    pub fn new() -> UserStatsMemoTypeStats {
        UserStatsMemoTypeStats {
            link_count: None,
            code_count: None,
            todo_count: None,
            undo_count: None,
        }
    }
}

