/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1Direction {
    #[serde(rename = "DIRECTION_UNSPECIFIED")]
    DirectionUnspecified,
    #[serde(rename = "ASC")]
    Asc,
    #[serde(rename = "DESC")]
    Desc,

}

impl std::fmt::Display for V1Direction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DirectionUnspecified => write!(f, "DIRECTION_UNSPECIFIED"),
            Self::Asc => write!(f, "ASC"),
            Self::Desc => write!(f, "DESC"),
        }
    }
}

impl Default for V1Direction {
    fn default() -> V1Direction {
        Self::DirectionUnspecified
    }
}

