/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1InboxType {
    #[serde(rename = "TYPE_UNSPECIFIED")]
    TypeUnspecified,
    #[serde(rename = "MEMO_COMMENT")]
    MemoComment,
    #[serde(rename = "VERSION_UPDATE")]
    VersionUpdate,

}

impl std::fmt::Display for V1InboxType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TypeUnspecified => write!(f, "TYPE_UNSPECIFIED"),
            Self::MemoComment => write!(f, "MEMO_COMMENT"),
            Self::VersionUpdate => write!(f, "VERSION_UPDATE"),
        }
    }
}

impl Default for V1InboxType {
    fn default() -> V1InboxType {
        Self::TypeUnspecified
    }
}

