/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListAllUserStatsResponse {
    #[serde(rename = "userStats", skip_serializing_if = "Option::is_none")]
    pub user_stats: Option<Vec<models::V1UserStats>>,
}

impl V1ListAllUserStatsResponse {
    pub fn new() -> V1ListAllUserStatsResponse {
        V1ListAllUserStatsResponse {
            user_stats: None,
        }
    }
}

