/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListUserAccessTokensResponse {
    #[serde(rename = "accessTokens", skip_serializing_if = "Option::is_none")]
    pub access_tokens: Option<Vec<models::V1UserAccessToken>>,
}

impl V1ListUserAccessTokensResponse {
    pub fn new() -> V1ListUserAccessTokensResponse {
        V1ListUserAccessTokensResponse {
            access_tokens: None,
        }
    }
}

