/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListMemoRelationsResponse {
    #[serde(rename = "relations", skip_serializing_if = "Option::is_none")]
    pub relations: Option<Vec<models::V1MemoRelation>>,
}

impl V1ListMemoRelationsResponse {
    pub fn new() -> V1ListMemoRelationsResponse {
        V1ListMemoRelationsResponse {
            relations: None,
        }
    }
}

