/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListShortcutsResponse {
    #[serde(rename = "shortcuts", skip_serializing_if = "Option::is_none")]
    pub shortcuts: Option<Vec<models::Apiv1Shortcut>>,
}

impl V1ListShortcutsResponse {
    pub fn new() -> V1ListShortcutsResponse {
        V1ListShortcutsResponse { shortcuts: None }
    }
}
