/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListInboxesResponse {
    #[serde(rename = "inboxes", skip_serializing_if = "Option::is_none")]
    pub inboxes: Option<Vec<models::V1Inbox>>,
    /// A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl V1ListInboxesResponse {
    pub fn new() -> V1ListInboxesResponse {
        V1ListInboxesResponse {
            inboxes: None,
            next_page_token: None,
        }
    }
}

