/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListMemoReactionsResponse {
    #[serde(rename = "reactions", skip_serializing_if = "Option::is_none")]
    pub reactions: Option<Vec<models::V1Reaction>>,
}

impl V1ListMemoReactionsResponse {
    pub fn new() -> V1ListMemoReactionsResponse {
        V1ListMemoReactionsResponse {
            reactions: None,
        }
    }
}

