/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Reaction {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
    /// The content identifier. For memo, it should be the `Memo.name`.
    #[serde(rename = "contentId", skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    #[serde(rename = "reactionType", skip_serializing_if = "Option::is_none")]
    pub reaction_type: Option<String>,
}

impl V1Reaction {
    pub fn new() -> V1Reaction {
        V1Reaction {
            id: None,
            creator: None,
            content_id: None,
            reaction_type: None,
        }
    }
}

