/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1RestoreMarkdownNodesResponse {
    #[serde(rename = "markdown", skip_serializing_if = "Option::is_none")]
    pub markdown: Option<String>,
}

impl V1RestoreMarkdownNodesResponse {
    pub fn new() -> V1RestoreMarkdownNodesResponse {
        V1RestoreMarkdownNodesResponse {
            markdown: None,
        }
    }
}

