/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SsoCredentials {
    /// The ID of the SSO provider.
    #[serde(rename = "idpId", skip_serializing_if = "Option::is_none")]
    pub idp_id: Option<i32>,
    /// The code to sign in with.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// The redirect URI.
    #[serde(rename = "redirectUri", skip_serializing_if = "Option::is_none")]
    pub redirect_uri: Option<String>,
}

impl V1SsoCredentials {
    pub fn new() -> V1SsoCredentials {
        V1SsoCredentials {
            idp_id: None,
            code: None,
            redirect_uri: None,
        }
    }
}
