/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1State {
    #[serde(rename = "STATE_UNSPECIFIED")]
    StateUnspecified,
    #[serde(rename = "NORMAL")]
    Normal,
    #[serde(rename = "ARCHIVED")]
    Archived,
}

impl std::fmt::Display for V1State {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StateUnspecified => write!(f, "STATE_UNSPECIFIED"),
            Self::Normal => write!(f, "NORMAL"),
            Self::Archived => write!(f, "ARCHIVED"),
        }
    }
}

impl Default for V1State {
    fn default() -> V1State {
        Self::StateUnspecified
    }
}
