/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 * Generated by: https://openapi-generator.tech
 */

use super::super::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1UnorderedListItemNode {
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "indent", skip_serializing_if = "Option::is_none")]
    pub indent: Option<i32>,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::V1Node>>,
}

impl V1UnorderedListItemNode {
    pub fn new() -> V1UnorderedListItemNode {
        V1UnorderedListItemNode {
            symbol: None,
            indent: None,
            children: None,
        }
    }
}
